### ISSUE TITLE
Incompatible i18next v2.0.1

### ISSUE THREAD

**Issue by reevelau** [i18next/ng-i18next#103]
i18next has been upgraded to 2.0.1 2 days ago. The update breaks interface that ng-i18next depending on.

When the issue triggered, angular will catch an exception and print to console as the following.

`Uncaught TypeError: i18n.lng is not a function`

workaround, to downgrade the i18next to previous version
bower install i18next#1.10.2

**Comment by ivanisko** [comment]
I agree, i got same problem.

**Comment by archer96** [comment]
There is now another branch, see: https://github.com/i18next/ng-i18next/tree/i18next-v2 which supports `i18next` v2 (all tests pass and all examples work).
I would call it a workaround since `ng-i18next` needs a rewrite for `i18next` v2 and `angular` v2.

But I'm not sure whether I will do this in the near future (see #104 )

Regards,
Andre

**Comment by anwalkers** [comment]
Now compatible with the latest version of i18next. See upgrade instructions in the readme
