### ISSUE TITLE
Usage with angular and browserify

### ISSUE THREAD

**Issue by kopax** [i18next/ng-i18next#65]
I am a bit confused,

i18next website tells me do install "i18next-client"  instead of "i18next" to use with browserify.

Which version should I use ?

I am interested to use your code, but I can't install it with npm, is there a way to get this work in a later released ?

**Comment by archer96** [comment]
It's been almost two months after the last answer to this question, so I'll close this now.

You are free to reopen this issue :)

**Comment by kcaron-cst** [comment]
I see a [`package.json`](https://github.com/i18next/ng-i18next/blob/master/package.json) but this module does [not seem to be published via NPM](https://www.npmjs.com/package/ng-i18next). Wondering if this was a conscious choice.

A bit of context -- I am exploring options with removing bower after reading [this article](https://gofore.com/ohjelmistokehitys/stop-using-bower/). `ng-i18next` is the only package in my ~20 depedency `bower.json` that doesn't seem to have a published NPM package.

**Comment by jamuhl** [comment]
@archer96 as i don't maintain this project should i transfer ownership to you?

**Comment by archer96** [comment]
I've now a npmjs account: https://www.npmjs.com/~archer96

@kcaron-cst Well, it was not a conscious choice... I simply never used `i18next` or `ng-i18next` with NPM because I always used `bower` for these packages. I haven't tried browserify, so I can't even say for sure if `ng-i18next` works with it or with Node.js. I'll reopen this issue until `ng-i18next` works and is tested with `browserify`.

@jamuhl :+1: 

Regards,
Andre

**Comment by jamuhl** [comment]
@archer96 ownership transfered

**Comment by kencaron** [comment]
@archer96 sorry for just going ahead and publishing it. Bower has bitten me quite a few times with our continuous integration. It's a lot easier for us to just maintain one package manager and freeze versions. No code changes are needed at all, it is working great so far. Thanks.
