### ISSUE TITLE
Question: Unit-testing in angular issue, $i18next filter not resolving.

### ISSUE THREAD

**Issue by vprasanth** [i18next/ng-i18next#88]
So I'm writing unit tests for a service which uses $i18next filter to set up some strings in an object, however when unit testing the service, the strings aren't resolved. I noticed in the README it says *`For testing purposes set up a server. Don't open your files directly because i18next then fails to load the language files!`*, but I'm not 100% sure if that is the reason my filters aren't resolving in the service during unit tests. Can someone please expand on that or shed some light on unit testing components that use $i18next? I'm pretty new to unit-testing and haven't gotten any answers so far from google, stack, or the irc channels. 

Sorry and thanks! 

Note. My gruntfile is set-up to include the i18next and ng-i18next as dependencies.

**Comment by archer96** [comment]
Hello,

I'm sorry for not answering earlier... :/
To be honest, I'm not that good at unit testing, too. :/

But in our unit tests we don't load *.json translation files but instead put them directly in the *.js file. See: https://github.com/i18next/ng-i18next/blob/master/test/unit/i18nextDirectiveSpec.js#L11-L43

I couldn't get it to work with loading *.json files and haven't tried since
 I'm sorry, but I don't think that I'm capable of helping you on this topic. :disappointed: 

Regards,
Andre

**Comment by anwalkers** [comment]
I am interested in what you are testing. It sounds like your problem has more to do with i18next and not ng-i18next...
