### ISSUE TITLE
ng-i18next is not working under 1.10.1 i18next

### ISSUE THREAD

**Issue by calamarico** [i18next/ng-i18next#91]
Since I did bower update and i18next reference changes to new version 1.10.1, ng-i18next stop working

**Comment by archer96** [comment]
Oh :/

There is a breaking change in `i18next` since version `1.10.0`. See: https://github.com/i18next/i18next/blob/master/CHANGELOG.md#1100

Change line [45](https://github.com/i18next/ng-i18next/blob/master/dist/ng-i18next.js#L45) of `ng-i18next.js` to:

```js
i18n.init(options, function (err, localize) {
```` 

I'll fix this immediately.

Regards,
Andre

**Comment by calamarico** [comment]
Ok! thanks @archer96, no problem i can wait for the fix, meanwhile i have changes the dependencies to 1.9.0 i18next. Thanks for being so fast

**Comment by archer96** [comment]
Done. Version `0.5.0` of `ng-i18next` is now online and should work ;)
Thanks for reporting this issue. :)

Regards,
Andre
